# this file overrides docker-compose.yml. the should be run together, e.g.
#   docker-compose -f docker-compose.yml -f docker-compose.debug.yml up

version: "3.8"

services:
  adminer:
    image: adminer:4.17.1
    restart: always
    ports:
      - 8080:8080

  postgresdb:
    ports:
      - 5432:5432

  server:
    build:
      context: .
      args:
        - NODE_ENV=development
    environment:
      - NODE_ENV=development      