version: '3.8'
services:      
  server:
    build:
      context: ./server
      args:
        - NODE_ENV=production
    environment:
      - NODE_ENV=production
      
  nginx:
    restart: always  # Ensure Nginx always restarts in production