version: "3.4"

#x-common-variables: &common-variables
#  POSTGRES_USER: postgres
#  POSTGRES_PASSWORD: password

volumes:
  pg_sandbox_data:
  pg_development_data:
  server_data:

services:
  postgresdb:
    image: postgres:16.2
    restart: unless-stopped
    ports:
      - 5432:5432
    env_file: ./.env
    volumes:
      - ./db-data:/var/lib/postgres
      - ./database/create.sql:/docker-entrypoint-initdb.d/create.sql

  adminer:
    image: adminer:4.8.1
    restart: always
    ports:
      - 8080:8080      

  server:
    build: ./server
    env_file: ./.env
    restart: unless-stopped
    ports:
      - 5001:5001
      - 80:5001
      - 443:443
    environment:
      PLAID_CLIENT_ID:
      PLAID_SECRET_SANDBOX:
      PLAID_SECRET_DEVELOPMENT:
      PLAID_SANDBOX_REDIRECT_URI:
      PLAID_DEVELOPMENT_REDIRECT_URI:
      PLAID_ENV:
      PORT: 5001
      DB_PORT: 5432
      DB_HOST_NAME: postgresdb
      NODE_ENV: development
    depends_on:
      - postgresdb
    stdin_open: true
    tty: true
    volumes:
      - ./server:/opt/server  # <- Breaks bccrypt and discouraged generally
      - /opt/server/node_modules # anonymous volume for node_modules only
      - ./server/static:/opt/server/static # Mount the static folder only
      - ${SSL_CERT_PATH}:${SSL_CERT_PATH}:ro
      - ${SSL_KEY_PATH}:${SSL_KEY_PATH}:ro
networks:
  app-network:
    driver: bridge