openapi: 3.0.3
info:
  title: Bablo app API.
  version: 1.0.0
servers:
  - url: http://babloapp.com:5001
    description: Main (production) server
  #- url: http://staging-api.example.com
  #  description: Optional server description, e.g. Internal staging server for testing
paths:
  /users/register:
    post:
      summary: Registers a new user.
      responses:
        '2XX':    # status code
          description: A JSON array of user names
          content:
            application/json:
              schema: 
                type: array
                items: 
                  type: string