-- Persistent Coach missions.
--
-- Slice #2 keeps this intentionally narrow: one mission type ("3-day coffee cap")
-- that can be started from Coach, tracked against discretionary spend, and completed
-- by stashing the saved amount into an existing savings goal.

CREATE TABLE IF NOT EXISTS public.coach_missions_table (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES public.profiles_table(id) ON DELETE CASCADE,
  mission_type TEXT NOT NULL CHECK (mission_type IN ('coffee_cap')),
  title TEXT NOT NULL DEFAULT '3-day coffee cap',
  icon TEXT NOT NULL DEFAULT '☕',
  target_match TEXT NOT NULL DEFAULT 'coffee',
  target_goal_id INTEGER REFERENCES public.savings_goals_table(id) ON DELETE SET NULL,
  start_date DATE NOT NULL DEFAULT CURRENT_DATE,
  end_date DATE NOT NULL,
  daily_cap NUMERIC(12, 2) NOT NULL DEFAULT 0,
  projected_savings NUMERIC(12, 2) NOT NULL DEFAULT 0,
  actual_savings NUMERIC(12, 2) NOT NULL DEFAULT 0,
  status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'completed', 'dismissed', 'cancelled')),
  completed_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT coach_missions_positive_window CHECK (end_date >= start_date),
  CONSTRAINT coach_missions_non_negative_amounts CHECK (
    daily_cap >= 0
    AND projected_savings >= 0
    AND actual_savings >= 0
  )
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_coach_missions_one_active_type
  ON public.coach_missions_table(user_id, mission_type)
  WHERE status = 'active';

CREATE INDEX IF NOT EXISTS idx_coach_missions_user_status
  ON public.coach_missions_table(user_id, status, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_coach_missions_target_goal
  ON public.coach_missions_table(target_goal_id);

DROP TRIGGER IF EXISTS set_timestamp_coach_missions
  ON public.coach_missions_table;
CREATE TRIGGER set_timestamp_coach_missions
  BEFORE UPDATE ON public.coach_missions_table
  FOR EACH ROW
  EXECUTE FUNCTION public.trigger_set_timestamp();

ALTER TABLE public.coach_missions_table ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users can view their own coach missions"
  ON public.coach_missions_table;
CREATE POLICY "Users can view their own coach missions"
  ON public.coach_missions_table
  FOR SELECT
  TO authenticated
  USING ((SELECT auth.uid()) = user_id);

DROP POLICY IF EXISTS "Users can insert their own coach missions"
  ON public.coach_missions_table;
CREATE POLICY "Users can insert their own coach missions"
  ON public.coach_missions_table
  FOR INSERT
  TO authenticated
  WITH CHECK (
    (SELECT auth.uid()) = user_id
    AND (
      target_goal_id IS NULL
      OR EXISTS (
        SELECT 1
        FROM public.savings_goals_table g
        WHERE g.id = target_goal_id
          AND g.user_id = (SELECT auth.uid())
      )
    )
  );

DROP POLICY IF EXISTS "Users can update their own coach missions"
  ON public.coach_missions_table;
CREATE POLICY "Users can update their own coach missions"
  ON public.coach_missions_table
  FOR UPDATE
  TO authenticated
  USING ((SELECT auth.uid()) = user_id)
  WITH CHECK (
    (SELECT auth.uid()) = user_id
    AND (
      target_goal_id IS NULL
      OR EXISTS (
        SELECT 1
        FROM public.savings_goals_table g
        WHERE g.id = target_goal_id
          AND g.user_id = (SELECT auth.uid())
      )
    )
  );

DROP POLICY IF EXISTS "Users can delete their own coach missions"
  ON public.coach_missions_table;
CREATE POLICY "Users can delete their own coach missions"
  ON public.coach_missions_table
  FOR DELETE
  TO authenticated
  USING ((SELECT auth.uid()) = user_id);

GRANT SELECT, INSERT, UPDATE, DELETE ON public.coach_missions_table TO authenticated;
GRANT USAGE, SELECT ON SEQUENCE public.coach_missions_table_id_seq TO authenticated;

CREATE OR REPLACE FUNCTION public.coach_mission_matches(
  p_mission_type TEXT,
  p_target_match TEXT,
  p_name TEXT,
  p_merchant_name TEXT,
  p_personal_finance_category TEXT,
  p_personal_finance_subcategory TEXT
)
RETURNS BOOLEAN
LANGUAGE sql
STABLE
SET search_path = public
AS $$
  SELECT CASE
    WHEN p_mission_type = 'coffee_cap' THEN
      COALESCE(p_personal_finance_subcategory, '') = 'FOOD_AND_DRINK_COFFEE'
      OR (
        COALESCE(p_personal_finance_category, '') = 'FOOD_AND_DRINK'
        AND LOWER(
          COALESCE(p_name, '') || ' ' ||
          COALESCE(p_merchant_name, '')
        ) LIKE ANY (ARRAY[
          '%coffee%',
          '%cafe%',
          '%café%',
          '%starbucks%',
          '%philz%',
          '%blue bottle%',
          '%peet%'
        ])
      )
    ELSE FALSE
  END;
$$;

CREATE OR REPLACE FUNCTION public.coach_mission_to_json(p_mission_id BIGINT)
RETURNS JSONB
LANGUAGE sql
SECURITY INVOKER
SET search_path = public
AS $$
  WITH mission AS (
    SELECT m.*, g.name AS goal_name
    FROM public.coach_missions_table m
    LEFT JOIN public.savings_goals_table g
      ON g.id = m.target_goal_id
     AND g.user_id = m.user_id
    WHERE m.id = p_mission_id
      AND m.user_id = (SELECT auth.uid())
  ),
  stats AS (
    SELECT
      m.id,
      GREATEST(1, (m.end_date - m.start_date + 1))::INTEGER AS total_days,
      COALESCE((
        SELECT COUNT(*)::INTEGER
        FROM generate_series(
          m.start_date,
          LEAST(CURRENT_DATE, m.end_date),
          INTERVAL '1 day'
        ) AS d(day)
        WHERE COALESCE((
          SELECT SUM(vt.amount)
          FROM public.variable_transactions vt
          WHERE vt.user_id = m.user_id
            AND vt.date = d.day::DATE
            AND public.coach_mission_matches(
              m.mission_type,
              m.target_match,
              vt.name,
              vt.merchant_name,
              vt.personal_finance_category,
              vt.personal_finance_subcategory
            )
        ), 0) <= m.daily_cap
      ), 0)::INTEGER AS completed_days
    FROM mission m
  )
  SELECT jsonb_build_object(
    'id', m.id,
    'user_id', m.user_id,
    'mission_type', m.mission_type,
    'title', m.title,
    'icon', m.icon,
    'target_goal_id', m.target_goal_id,
    'goal_name', m.goal_name,
    'start_date', m.start_date,
    'end_date', m.end_date,
    'projected_savings', m.projected_savings,
    'actual_savings', m.actual_savings,
    'status', m.status,
    'completed_days', CASE
      WHEN m.status = 'completed' THEN s.total_days
      ELSE LEAST(s.completed_days, s.total_days)
    END,
    'total_days', s.total_days,
    'created_at', m.created_at,
    'updated_at', m.updated_at
  )
  FROM mission m
  JOIN stats s
    ON s.id = m.id;
$$;

CREATE OR REPLACE FUNCTION public.get_coach_missions()
RETURNS JSONB
LANGUAGE sql
SECURITY INVOKER
SET search_path = public
AS $$
  SELECT jsonb_build_object(
    'missions',
    COALESCE(
      jsonb_agg(
        public.coach_mission_to_json(m.id)
        ORDER BY
          CASE WHEN m.status = 'active' THEN 0 ELSE 1 END,
          m.created_at DESC
      ),
      '[]'::JSONB
    )
  )
  FROM public.coach_missions_table m
  WHERE m.user_id = (SELECT auth.uid())
    AND (
      m.status = 'active'
      OR m.created_at >= NOW() - INTERVAL '30 days'
    );
$$;

CREATE OR REPLACE FUNCTION public.start_coach_mission(
  p_mission_type TEXT DEFAULT 'coffee_cap',
  p_target_goal_id INTEGER DEFAULT NULL,
  p_projected_savings NUMERIC DEFAULT 24,
  p_daily_cap NUMERIC DEFAULT 0
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY INVOKER
SET search_path = public
AS $$
DECLARE
  v_user_id UUID := (SELECT auth.uid());
  v_existing_id BIGINT;
  v_mission_id BIGINT;
BEGIN
  IF v_user_id IS NULL THEN
    RAISE EXCEPTION 'Authentication required';
  END IF;

  IF p_mission_type <> 'coffee_cap' THEN
    RAISE EXCEPTION 'Unsupported coach mission type: %', p_mission_type;
  END IF;

  IF p_target_goal_id IS NOT NULL THEN
    PERFORM 1
    FROM public.savings_goals_table g
    WHERE g.id = p_target_goal_id
      AND g.user_id = v_user_id
      AND g.is_active = TRUE;

    IF NOT FOUND THEN
      RAISE EXCEPTION 'Target goal does not belong to the current user';
    END IF;
  END IF;

  SELECT id
  INTO v_existing_id
  FROM public.coach_missions_table
  WHERE user_id = v_user_id
    AND mission_type = p_mission_type
    AND status = 'active'
  ORDER BY created_at DESC
  LIMIT 1;

  IF v_existing_id IS NOT NULL THEN
    RETURN public.coach_mission_to_json(v_existing_id);
  END IF;

  INSERT INTO public.coach_missions_table (
    user_id,
    mission_type,
    title,
    icon,
    target_match,
    target_goal_id,
    start_date,
    end_date,
    daily_cap,
    projected_savings,
    status
  )
  VALUES (
    v_user_id,
    p_mission_type,
    '3-day coffee cap',
    '☕',
    'coffee',
    p_target_goal_id,
    CURRENT_DATE,
    CURRENT_DATE + 2,
    GREATEST(0, p_daily_cap),
    GREATEST(0, p_projected_savings),
    'active'
  )
  RETURNING id INTO v_mission_id;

  RETURN public.coach_mission_to_json(v_mission_id);
END;
$$;

CREATE OR REPLACE FUNCTION public.complete_coach_mission(
  p_mission_id BIGINT,
  p_actual_savings NUMERIC DEFAULT NULL,
  p_stash BOOLEAN DEFAULT FALSE
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY INVOKER
SET search_path = public
AS $$
DECLARE
  v_user_id UUID := (SELECT auth.uid());
  v_mission public.coach_missions_table%ROWTYPE;
  v_actual NUMERIC;
  v_deposit JSONB := NULL;
BEGIN
  IF v_user_id IS NULL THEN
    RAISE EXCEPTION 'Authentication required';
  END IF;

  SELECT *
  INTO v_mission
  FROM public.coach_missions_table
  WHERE id = p_mission_id
    AND user_id = v_user_id
    AND status = 'active'
  FOR UPDATE;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Active coach mission not found';
  END IF;

  v_actual := GREATEST(0, COALESCE(p_actual_savings, v_mission.projected_savings));

  UPDATE public.coach_missions_table
  SET
    status = 'completed',
    actual_savings = v_actual,
    completed_at = NOW()
  WHERE id = v_mission.id;

  IF p_stash AND v_mission.target_goal_id IS NOT NULL AND v_actual > 0 THEN
    INSERT INTO public.savings_deposits_table (
      goal_id,
      user_id,
      amount,
      deposit_date
    )
    VALUES (
      v_mission.target_goal_id,
      v_user_id,
      v_actual,
      CURRENT_DATE
    )
    RETURNING jsonb_build_object(
      'id', id,
      'goal_id', goal_id,
      'user_id', user_id,
      'amount', amount,
      'deposit_date', deposit_date,
      'created_at', created_at
    )
    INTO v_deposit;
  END IF;

  RETURN jsonb_build_object(
    'mission', public.coach_mission_to_json(v_mission.id),
    'deposit', v_deposit
  );
END;
$$;

REVOKE EXECUTE ON FUNCTION public.coach_mission_matches(TEXT, TEXT, TEXT, TEXT, TEXT, TEXT) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.coach_mission_to_json(BIGINT) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.get_coach_missions() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.start_coach_mission(TEXT, INTEGER, NUMERIC, NUMERIC) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.complete_coach_mission(BIGINT, NUMERIC, BOOLEAN) FROM PUBLIC;

REVOKE EXECUTE ON FUNCTION public.coach_mission_matches(TEXT, TEXT, TEXT, TEXT, TEXT, TEXT) FROM anon;
REVOKE EXECUTE ON FUNCTION public.coach_mission_to_json(BIGINT) FROM anon;
REVOKE EXECUTE ON FUNCTION public.get_coach_missions() FROM anon;
REVOKE EXECUTE ON FUNCTION public.start_coach_mission(TEXT, INTEGER, NUMERIC, NUMERIC) FROM anon;
REVOKE EXECUTE ON FUNCTION public.complete_coach_mission(BIGINT, NUMERIC, BOOLEAN) FROM anon;

GRANT EXECUTE ON FUNCTION public.coach_mission_matches(TEXT, TEXT, TEXT, TEXT, TEXT, TEXT) TO authenticated;
GRANT EXECUTE ON FUNCTION public.coach_mission_to_json(BIGINT) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_coach_missions() TO authenticated;
GRANT EXECUTE ON FUNCTION public.start_coach_mission(TEXT, INTEGER, NUMERIC, NUMERIC) TO authenticated;
GRANT EXECUTE ON FUNCTION public.complete_coach_mission(BIGINT, NUMERIC, BOOLEAN) TO authenticated;
